export const API = {
  AUTH: {
    REGISTER: '/api/v1/auth/register',
    VERIFY_OTP: '/api/v1/auth/verify-otp',
    RESEND_OTP: '/api/v1/auth/resend-otp',
    LOGIN: '/api/v1/auth/login',
    REFRESH: '/api/v1/auth/refresh-token',
    LOGOUT: '/api/v1/auth/logout',
    FORGOT_PASSWORD: '/api/v1/auth/forgot-password',
    RESET_PASSWORD: '/api/v1/auth/reset-password',
  },
  PRODUCTS: {
    LIST: '/api/v1/products',
    DETAILS: (id) => `/api/v1/products/${id}`,
    BY_CATEGORY: (id) => `/api/v1/products/category/${id}`,
  },
  CATEGORIES: {
    LIST: '/api/v1/categories',
    DETAILS: (id) => `/api/v1/categories/${id}`,
  },
  CUSTOMER: {
    PROFILE: '/api/v1/customer/profile',
    CHANGE_PASSWORD: '/api/v1/customer/change-password',
    ADDRESSES: '/api/v1/customer/addresses',
    ADDRESS: (id) => `/api/v1/customer/addresses/${id}`,
    ADDRESS_DEFAULT: (id) => `/api/v1/customer/addresses/${id}/default`,
    CART: '/api/v1/customer/cart',
    CART_ITEMS: '/api/v1/customer/cart/items',
    CART_ITEM: (id) => `/api/v1/customer/cart/items/${id}`,
    ORDERS: '/api/v1/customer/orders',
    ORDER: (id) => `/api/v1/customer/orders/${id}`,
    CHECKOUT: '/api/v1/customer/orders/checkout',
    ORDER_CANCEL: (id) => `/api/v1/customer/orders/${id}/cancel`,
    PAYMENT_CREATE: (orderId) => `/api/v1/customer/orders/${orderId}/payment/create`,
    PAYMENT_VERIFY: '/api/v1/customer/payments/verify',
    PAYMENTS: '/api/v1/customer/payments',
  },
  MERCHANT: {
    FIRST_LOGIN_CHANGE_PASSWORD: '/api/v1/merchant/first-login/change-password',
    CHANGE_PASSWORD: '/api/v1/merchant/change-password',
    PROFILE: '/api/v1/merchant/profile',
    PRODUCTS: '/api/v1/merchant/products',
    PRODUCT: (id) => `/api/v1/merchant/products/${id}`,
    PRODUCT_IMAGES: (id) => `/api/v1/merchant/products/${id}/images`,
    PRODUCT_STOCK: (id) => `/api/v1/merchant/products/${id}/stock`,
  },
  ADMIN: {
    MERCHANTS: '/api/v1/admin/merchants',
    MERCHANT: (id) => `/api/v1/admin/merchants/${id}`,
    MERCHANT_BLOCK: (id) => `/api/v1/admin/merchants/${id}/block`,
    MERCHANT_UNBLOCK: (id) => `/api/v1/admin/merchants/${id}/unblock`,
    CUSTOMERS: '/api/v1/admin/customers',
    CUSTOMER: (id) => `/api/v1/admin/customers/${id}`,
    CUSTOMER_BLOCK: (id) => `/api/v1/admin/customers/${id}/block`,
    CUSTOMER_UNBLOCK: (id) => `/api/v1/admin/customers/${id}/unblock`,
    PRODUCTS: '/api/v1/admin/products',
    PRODUCT_APPROVE: (id) => `/api/v1/admin/products/${id}/approve`,
    PRODUCT_REJECT: (id) => `/api/v1/admin/products/${id}/reject`,
    CATEGORIES: '/api/v1/admin/categories',
    CATEGORY: (id) => `/api/v1/admin/categories/${id}`,
  },
}

export const ROLES = {
  ADMIN: 'ADMIN',
  MERCHANT: 'MERCHANT',
  CUSTOMER: 'CUSTOMER',
}
